#what is the gol of workflow
#goal:whenever someone changes the python code, the linter will check the syntax,format,indentaion

name: Auto Linter

on:
  push:
    paths:
      - "*.py"

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/clone the code
        uses: actions/checkout@v4

      - name: Install Linter
        run: pip install ruff

      - name: Check the files for linting
        run: ruff check .
